-- 1. Create the MARINE_OBSERVATION table
CREATE TABLE MARINE_OBSERVATION (
    OBSERVATION_ID INTEGER PRIMARY KEY,
    SPECIES_NAME TEXT NOT NULL,
    ANIMAL_GROUP TEXT NOT NULL,
    DEPTH_METERS REAL NOT NULL,
    EST_WEIGHT_KG REAL NOT NULL
);

-- 2. Insert sample marine observation records
INSERT INTO MARINE_OBSERVATION VALUES (1, 'Blue Whale', 'Mammal', 150.0, 140000.0);
INSERT INTO MARINE_OBSERVATION VALUES (2, 'Bottlenose Dolphin', 'Mammal', 20.0, 300.0);
INSERT INTO MARINE_OBSERVATION VALUES (3, 'Great White Shark', 'Fish', 50.0, 1100.0);
INSERT INTO MARINE_OBSERVATION VALUES (4, 'Manta Ray', 'Fish', 30.0, 1300.0);
INSERT INTO MARINE_OBSERVATION VALUES (5, 'Manta Ray', 'Fish', 45.0, 1250.0);
INSERT INTO MARINE_OBSERVATION VALUES (6, 'Sea Turtle', 'Reptile', 15.0, 400.0);
INSERT INTO MARINE_OBSERVATION VALUES (7, 'Giant Squid', 'Mollusk', 800.0, 270.0);
INSERT INTO MARINE_OBSERVATION VALUES (8, 'Orca', 'Mammal', 100.0, 5000.0);

-- Display all recorded observations
SELECT * FROM MARINE_OBSERVATION;

-- 3. Unique Animal Groups: Find distinct groups & count them
SELECT DISTINCT ANIMAL_GROUP FROM MARINE_OBSERVATION;

SELECT COUNT(DISTINCT ANIMAL_GROUP) AS UNIQUE_ANIMAL_GROUPS 
FROM MARINE_OBSERVATION;

-- 4. COUNT: Total observations and deep-sea observations (> 40m)
SELECT COUNT(OBSERVATION_ID) AS TOTAL_OBSERVATIONS 
FROM MARINE_OBSERVATION;

SELECT COUNT(OBSERVATION_ID) AS DEEP_OBSERVATIONS 
FROM MARINE_OBSERVATION 
WHERE DEPTH_METERS > 40.0;

-- 5. SUM & AVG: Total weight observed and average depth
SELECT SUM(EST_WEIGHT_KG) AS TOTAL_WEIGHT_KG 
FROM MARINE_OBSERVATION;

SELECT AVG(DEPTH_METERS) AS AVG_DEPTH_METERS 
FROM MARINE_OBSERVATION;

-- 6. Combined Query: Summary of all aggregate metrics
SELECT 
    COUNT(OBSERVATION_ID) AS TOTAL_OBSERVATIONS,
    COUNT(DISTINCT ANIMAL_GROUP) AS UNIQUE_GROUPS,
    SUM(EST_WEIGHT_KG) AS TOTAL_WEIGHT_KG,
    AVG(DEPTH_METERS) AS AVG_DEPTH_METERS
FROM MARINE_OBSERVATION;